#!/bin/sh
# Serves https://<any host>/<path> from $FAKE_SITE/<path>, to -o or stdout.
set -eu
printf 'curl %s\n' "$*" >> "$FAKE_LOG"
dest=""
url=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o)
      dest="$2"
      shift 2
      ;;
    https://*)
      url="$1"
      shift
      ;;
    *)
      shift
      ;;
  esac
done
src="$FAKE_SITE/${url#https://*/}"
src="${src%%\?*}"
if [ ! -f "$src" ]; then
  exit 22
fi
if [ -n "$dest" ]; then
  cp "$src" "$dest"
else
  cat "$src"
fi
